# Generated by Django 2.2.1 on 2019-05-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=150)),
                ('cartao', models.IntegerField()),
                ('pagamento', models.CharField(choices=[('av', 'pagamento a vista'), ('p2', 'parcela duas vezes'), ('p3', 'parcela tres vezes'), ('p4', 'parcela quatro vezes'), ('p5', 'parcela cinco vezes')], default='av', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('em_estoque', models.BooleanField(default=True)),
            ],
        ),
    ]
